# vim:ft=ansible:
#
# Copyright (c) 2016 Jason McVetta <jason.mcvetta@gmail.com>.  This is Free
# Software, released under the terms of the GPL v3.  See
# http://www.gnu.org/copyleft/gpl.html for details.  Resist intellectual
# serfdom - the ownership of ideas is akin to slavery.
---

- name: Ensure rsyslog is installed (Debian)
  apt:
    name: rsyslog
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Ensure rsyslog is installed (RedHat)
  yum:
    name: rsyslog
    state: present
    update_cache: yes
  when: ansible_os_family == 'RedHat'

- name: Ensure rsyslog for tls config is present
  import_tasks: tls.yml
  when: rsyslog_tls | default('false') | bool
  changed_when: false

- name: Check for existing config files
  shell: ls -l {{ rsyslog_conf_path }} # noqa 305
  register: capture
  changed_when: false

- name: Remove unexpected rsyslog config files
  file: path={{ rsyslog_conf_path }}/{{ item }} state=absent
  with_items: "{{ capture.stdout_lines }}"
  when: item != rsyslog_conf_file
  ignore_errors: True

- name: Ensure rsyslog config is present
  template:
    src: 22-rsyslog.conf.j2
    dest: "{{ rsyslog_conf_path }}/{{ rsyslog_conf_file }}"
    mode: 0644
  notify: Restart rsyslog

- name: Check which init system is in place
  shell: cat /proc/1/status | grep '[Nn]ame'|sed 's/[Nn]ame:\s*//' # noqa 306
  register: init_system
  changed_when: false

# Ref: https://www.loggly.com/docs/systemd-logs/
- name: Configure systemd to forward logs to rsyslog
  import_tasks: journald.yml
  when: init_system.stdout == "systemd"
  ignore_errors: True
