name: master and pr builds
on:
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master
  workflow_dispatch:

jobs:
  build:
    name: Ansible lint
    runs-on: ubuntu-latest
    env:
      ANSIBLE_ROLES_PATH: ".:..:$PWD"
    steps:
    - uses: actions/checkout@v2
    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@master
      with:
        targets: "**/*.yml"
        override-deps: |
          ansible-lint==5.3.1
    - name: Install Dependencies
      run: pip install ansible
    - name: Run ansible syntax-check
      run: ansible-playbook tests/test.yml -i tests/inventory --syntax-check
